version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network


  app:
    image: omeritzhaki/user-auth-service:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
