app:
  image:
    repository: omeritzhaki/user-auth-service
    tag: latest

mysql:
  image:
    repository: omeritzhaki/custom-mysql-image
    tag: latest
  secretName: mysql-secret
  rootPassword: cGFzc3dvcmQ

